-- MySQL Script generated by MySQL Workbench
-- Tue May 29 15:28:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema workflow_engine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema workflow_engine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workflow_engine` DEFAULT CHARACTER SET utf8mb4 ;
USE `workflow_engine` ;

-- -----------------------------------------------------
-- Table `workflow_engine`.`action_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`action_type` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`process`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`process` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`action` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `action_type_id` BIGINT(20) NOT NULL,
  `process_id` BIGINT(20) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_action_action_type1_idx` (`action_type_id` ASC),
  INDEX `fk_action_process1_idx` (`process_id` ASC),
  CONSTRAINT `fk_action_action_type1`
    FOREIGN KEY (`action_type_id`)
    REFERENCES `workflow_engine`.`action_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_action_process1`
    FOREIGN KEY (`process_id`)
    REFERENCES `workflow_engine`.`process` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`group` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`target`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`target` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`action_target`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`action_target` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `action_id` BIGINT(20) NOT NULL,
  `target_id` BIGINT(20) NOT NULL,
  `group_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_action_target_action1_idx` (`action_id` ASC),
  INDEX `fk_action_target_target1_idx` (`target_id` ASC),
  INDEX `fk_action_target_group1_idx` (`group_id` ASC),
  CONSTRAINT `fk_action_target_action1`
    FOREIGN KEY (`action_id`)
    REFERENCES `workflow_engine`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_action_target_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `workflow_engine`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_action_target_target1`
    FOREIGN KEY (`target_id`)
    REFERENCES `workflow_engine`.`target` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`activity_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`activity_type` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`activity` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `activity_type_id` BIGINT(20) NOT NULL,
  `process_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_activity_activity_type1_idx` (`activity_type_id` ASC),
  INDEX `fk_activity_process1_idx` (`process_id` ASC),
  CONSTRAINT `fk_activity_activity_type1`
    FOREIGN KEY (`activity_type_id`)
    REFERENCES `workflow_engine`.`activity_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activity_process1`
    FOREIGN KEY (`process_id`)
    REFERENCES `workflow_engine`.`process` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`activity_target`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`activity_target` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `activity_id` BIGINT(20) NOT NULL,
  `target_id` BIGINT(20) NOT NULL,
  `group_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_activity_target_activity1_idx` (`activity_id` ASC),
  INDEX `fk_activity_target_target1_idx` (`target_id` ASC),
  INDEX `fk_activity_target_group1_idx` (`group_id` ASC),
  CONSTRAINT `fk_activity_target_activity1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `workflow_engine`.`activity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activity_target_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `workflow_engine`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activity_target_target1`
    FOREIGN KEY (`target_id`)
    REFERENCES `workflow_engine`.`target` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`user` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`group_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`group_member` (
  `group_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`group_id`, `user_id`),
  INDEX `fk_group_member_group1_idx` (`group_id` ASC),
  INDEX `fk_group_member_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_group_member_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `workflow_engine`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_member_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `workflow_engine`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`process_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`process_admin` (
  `process_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`process_id`, `user_id`),
  INDEX `fk_process_admin_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_pa_process`
    FOREIGN KEY (`process_id`)
    REFERENCES `workflow_engine`.`process` (`id`),
  CONSTRAINT `fk_process_admin_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `workflow_engine`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`state_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`state_type` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`state` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `state_type_id` BIGINT(20) NOT NULL,
  `process_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_state_state_type1_idx` (`state_type_id` ASC),
  INDEX `fk_state_process1_idx` (`process_id` ASC),
  CONSTRAINT `fk_state_process1`
    FOREIGN KEY (`process_id`)
    REFERENCES `workflow_engine`.`process` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_state_state_type1`
    FOREIGN KEY (`state_type_id`)
    REFERENCES `workflow_engine`.`state_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`request` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `process_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `current_state_id` BIGINT(20) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `date_requested` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_request_process1_idx` (`process_id` ASC),
  INDEX `fk_request_state1_idx` (`current_state_id` ASC),
  INDEX `fk_request_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_request_process1`
    FOREIGN KEY (`process_id`)
    REFERENCES `workflow_engine`.`process` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_state1`
    FOREIGN KEY (`current_state_id`)
    REFERENCES `workflow_engine`.`state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `workflow_engine`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`transition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`transition` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `process_id` BIGINT(20) NOT NULL,
  `current_state_id` BIGINT(20) NOT NULL,
  `next_state_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transition_process1_idx` (`process_id` ASC),
  INDEX `fk_transition_state1_idx` (`current_state_id` ASC),
  INDEX `fk_transition_state2_idx` (`next_state_id` ASC),
  CONSTRAINT `fk_transition_process1`
    FOREIGN KEY (`process_id`)
    REFERENCES `workflow_engine`.`process` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transition_state1`
    FOREIGN KEY (`current_state_id`)
    REFERENCES `workflow_engine`.`state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transition_state2`
    FOREIGN KEY (`next_state_id`)
    REFERENCES `workflow_engine`.`state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`request_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`request_action` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `request_id` BIGINT(20) NOT NULL,
  `transition_id` BIGINT(20) NOT NULL,
  `action_id` BIGINT(20) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `is_complete` TINYINT(1) NOT NULL DEFAULT '0',
  `completed_by` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_request_action_request1_idx` (`request_id` ASC),
  INDEX `fk_request_action_transition1_idx` (`transition_id` ASC),
  INDEX `fk_request_action_action1_idx` (`action_id` ASC),
  INDEX `fk_request_action_user1_idx` (`completed_by` ASC),
  CONSTRAINT `fk_request_action_action1`
    FOREIGN KEY (`action_id`)
    REFERENCES `workflow_engine`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_action_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `workflow_engine`.`request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_action_transition1`
    FOREIGN KEY (`transition_id`)
    REFERENCES `workflow_engine`.`transition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_action_user1`
    FOREIGN KEY (`completed_by`)
    REFERENCES `workflow_engine`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`request_stakeholder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`request_stakeholder` (
  `request_id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`request_id`, `user_id`),
  INDEX `fk_request_stakeholder_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_request_stakeholder_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `workflow_engine`.`request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_stakeholder_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `workflow_engine`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`state_activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`state_activity` (
  `state_id` BIGINT(20) NOT NULL,
  `activity_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`state_id`, `activity_id`),
  INDEX `fk_state_activity_activity1_idx` (`activity_id` ASC),
  CONSTRAINT `fk_state_activity_activity1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `workflow_engine`.`activity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_state_activity_state1`
    FOREIGN KEY (`state_id`)
    REFERENCES `workflow_engine`.`state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`transition_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`transition_action` (
  `transition_id` BIGINT(20) NOT NULL,
  `action_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`transition_id`, `action_id`),
  INDEX `fk_transition_action_transition1_idx` (`transition_id` ASC),
  INDEX `fk_transition_action_action1_idx` (`action_id` ASC),
  CONSTRAINT `fk_transition_action_action1`
    FOREIGN KEY (`action_id`)
    REFERENCES `workflow_engine`.`action` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transition_action_transition1`
    FOREIGN KEY (`transition_id`)
    REFERENCES `workflow_engine`.`transition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `workflow_engine`.`transition_activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workflow_engine`.`transition_activity` (
  `activity_id` BIGINT(20) NOT NULL,
  `transition_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`activity_id`, `transition_id`),
  INDEX `fk_transition_activity_activity1_idx` (`activity_id` ASC),
  INDEX `fk_transition_activity_transition1_idx` (`transition_id` ASC),
  CONSTRAINT `fk_transition_activity_activity1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `workflow_engine`.`activity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transition_activity_transition1`
    FOREIGN KEY (`transition_id`)
    REFERENCES `workflow_engine`.`transition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
